/* empty css                      */import{S as w,a as S,i as n}from"./assets/vendor-Bub99LOP.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const e=r.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),q.refresh()}function B(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function L(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}const $="55067966-cf05e757d51b20726f9c2f743",E="https://pixabay.com/api/";async function v(r,e=1){const o={key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await S.get(E,{params:o})).data}const M=document.querySelector(".form"),O=document.querySelector(".load-more");let c=1,i="",u=0,a=0;M.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements.searchQuery.value.trim(),!!i){c=1,a=0,B(),b(),p();try{const e=await v(i,c);if(e.hits.length===0){n.error({message:"Sorry, no images found."});return}u=e.totalHits,a+=e.hits.length,y(e.hits),a<u?L():n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Error loading images"})}finally{g()}}});O.addEventListener("click",async()=>{c+=1,b(),p();try{const r=await v(i,c);y(r.hits),a+=r.hits.length,I(),a<u?L():n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Error loading more images"})}finally{g()}});function I(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
